### ISSUE TITLE
Mobile view looks bad.

### ISSUE THREAD

**Issue by Animesh-Ghosh** [mridubhatnagar/rockpaperscissor#1]
This is what I saw in mobile view.

![image](https://user-images.githubusercontent.com/34956994/82246661-baea8d80-9962-11ea-982b-2fbf28350087.png)

 I think this can be improved with some CSS and media queries. Some things on the desktop view can also be changed.

**Comment by mridubhatnagar** [comment]
This is not mobile responsive currently. This is my first frontend project. I'll make it mobile responsive soon. 

I am yet to read, learn, explore media queries and related concepts. 

Thanks.

**Comment by mridubhatnagar** [comment]
@Animesh-Ghosh can you check the mobile view again. And update. I haven't added the media queries yet. But, have made some changes in the CSS.

**Comment by Animesh-Ghosh** [comment]
It's better than before. 👍
